- name: reload nginx 
  service:
    name: nginx
    state: reloaded
  become: true
  become_method: sudo

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: true
  become_method: sudo
