- name: "Check app"
  uri:
    url: http://{{server}}{{context}}
    return_content: yes
  register: app_page
  failed_when: "content not in app_page.content"

- name: "Show debug message"
  debug:
    msg: "App page is available"
